### ISSUE TITLE
Mark as waiting on author after CI fail, review after success

### ISSUE THREAD

**Issue by czipperz** [rust-lang/rust-log-analyzer#27]
Currently the high five bot will mark the PR as waiting on review once it is created.  But it would be more useful if it switched it back to author when the CI fails.  Then when it passes, it can switch back to waiting on review.

**Comment by kennytm** [comment]
1. This is marked as "waiting on review" because the error is potentially just a spurious error, not the author's fault, and we err on mistakes on our side.
2. These labels are managed by bors (homu), not RLA. The setting can be found in https://github.com/rust-lang/rust-central-station/blob/4236d45f9664fda0c1a7192fac6f15f68cf3f7c3/homu.toml.template#L62-L64.
